---
- name: Remove Grafana + Loki stack
  hosts: Red-Blue
  become: true
  gather_facts: false

  vars:
    docker_network: "monitoring_net"
    grafana_container_name: "grafana"
    loki_container_name: "loki"
    grafana_provisioning_dir: "/opt/grafana"

  tasks:
    - name: Stop and remove Grafana container
      community.docker.docker_container:
        name: "{{ grafana_container_name }}"
        state: absent
        force_kill: true

    - name: Stop and remove Loki container
      community.docker.docker_container:
        name: "{{ loki_container_name }}"
        state: absent
        force_kill: true

    - name: Remove monitoring Docker network
      community.docker.docker_network:
        name: "{{ docker_network }}"
        state: absent

    - name: Remove Grafana provisioning directory
      file:
        path: "{{ grafana_provisioning_dir }}"
        state: absent
