---
- name: Delete HashiCorp Vault completely
  hosts: HashiCorp
  gather_facts: true

  vars:
    vault_bin_path: "/usr/local/bin/vault"
    vault_config_dir: "/etc/vault.d"
    vault_data_dir: "/opt/vault/data"
    init_output_file: "/root/vault-init.json"

  tasks:
    - name: Stop Vault service
      ansible.builtin.systemd:
        name: vault
        state: stopped
        enabled: false
        masked: true

    - name: Remove Vault systemd service file
      ansible.builtin.file:
        path: "/etc/systemd/system/vault.service"
        state: absent

    - name: Reload systemd daemon
      ansible.builtin.command: systemctl daemon-reload

    - name: Remove Vault binary
      ansible.builtin.file:
        path: "{{ vault_bin_path }}"
        state: absent

    - name: Remove Vault config directory
      ansible.builtin.file:
        path: "{{ vault_config_dir }}"
        state: absent

    - name: Remove Vault data directory
      ansible.builtin.file:
        path: "{{ vault_data_dir }}"
        state: absent

    - name: Remove Vault init JSON file
      ansible.builtin.file:
        path: "{{ init_output_file }}"
        state: absent

    - name: Remove Vault profile script
      ansible.builtin.file:
        path: "/etc/profile.d/vault.sh"
        state: absent
